#@#@ Cluster Settings
cluster.name: 'es-cluster'
network.host: '0.0.0.0'
http.host: 0.0.0.0
bootstrap.memory_lock: true

node.name: tasks.elasticsearch1
discovery.seed_hosts: ["tasks.elasticsearch3", "tasks.elasticsearch2"]
cluster.initial_master_nodes: ["tasks.elasticsearch1", "tasks.elasticsearch2", "tasks.elasticsearch3"] 

xpack.ml.enabled: false #? Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false]

#@#@ License
xpack.license.self_generated.type: trial #? free Xpack license 30 days

#@ Security
xpack.security.enabled: true #? default: authentication feature
xpack.security.authc.token.enabled: true #? enable auth by token
xpack.security.authc.api_key.enabled: true #? enable auth by api_key

#@ transport security settings
#@ This is mostly used for inter-node communications between parts of the ELK stack
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: ${CONFIG_DIR}/elasticsearch.key
xpack.security.transport.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
xpack.security.transport.ssl.verification_mode: certificate

#@ HTTP security setttings
#@ This is used for client server ssl/tls communications (e.g. browser, kibana)
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: ${CONFIG_DIR}/elasticsearch.key
xpack.security.http.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
