services:
    elasticsearch1:
        hostname: elasticsearch1
        user: '1001:1001'
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn1
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
        # ports:
        #     - '9200:9200'
        # ports:
        # - target: 9200
        #   published: 9200
        #   protocol: tcp
        #   mode: ingress
        healthcheck:
            test: curl -s -k https://elasticsearch1:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk
        deploy:
            endpoint_mode: dnsrr
            mode: replicated

    elasticsearch2:
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn2
        hostname: elasticsearch2
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
        healthcheck:
            test: curl -s -k https://elasticsearch2:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk
        deploy:
            endpoint_mode: dnsrr
            mode: replicated

    elasticsearch3:
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn3
        hostname: elasticsearch3
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
        healthcheck:
            test: curl -s -k https://elasticsearch3:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk
        deploy:
            endpoint_mode: dnsrr
            mode: replicated

    kibana:
        hostname: kibana
        image: maverick0809/bitnami_kibana_tls:8.15.3v1
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/kibana/config
            ENCRYPTION_KEY: ${XPACK_ENCRYPTION_KEY}
            KIBANA_ELASTICSEARCH_URL: 'https://${ELASTIC_HOST}:9200'
            KIBANA_URL: https://0.0.0.0:5601
            KIBANA_HOST: 0.0.0.0
            KIBANA_PORT_NUMBER: 5601
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        volumes:
            - 'kibana_data:/bitnami/kibana'
            - 'kibana_conf:/opt/bitnami/kibana/config'
        healthcheck:
            test: curl -s -k https://kibana:5601 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
            - '5601:5601'
        networks:
            - efk
        depends_on:
            - elasticsearch1
            - elasticsearch2
            - elasticsearch3

    fluentd:
        image: maverick0809/bitnami_fluentd_tls:1.17.1v1
        user: '0:0'
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
            ELASTIC_HOST: ${ELASTIC_HOST}
            ELASTICSEARCH_URL: 'https://${ELASTIC_HOST}:9200'
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers
            - fluentd_conf:/opt/bitnami/fluentd/conf/
        depends_on:
            - elasticsearch1
            - elasticsearch2
            - elasticsearch3
        networks:
            - efk

networks:
    efk:
        driver: overlay

volumes:
    elasticsearch_data:
        driver: local
    elasticsearch_conf:
        driver: local
    fluentd_conf:
        driver: local
    kibana_data:
        driver: local
    kibana_conf:
        driver: local
