services:
    certs:
        container_name: certs
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
        command: bash ${ELASTIC_DIR}/config/setup.sh
        user: '0'
        volumes:
            - ./secrets:/secrets/
            - ./helper/setup.sh:${ELASTIC_DIR}/config/setup.sh
            - ./helper/instances.yml:${ELASTIC_DIR}/config/instances.yml:ro
        environment:
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
            SUBDOMAIN: ${SUBDOMAIN}
            SUBFOLDER: ${SUBFOLDER}
            STAGING: ${STAGING}
