all:
    hosts:
        srv_01:
            ansible_host: 192.168.33.10
            ansible_user: '{{ssh_user}}'
            ansible_ssh_pass: '{{ssh_pass}}'
            dest_path: "{{ {{dest_path}} | default('~/') }}"
        srv_02:
            ansible_host: 192.168.33.11
            ansible_user: '{{ssh_user}}'
            ansible_ssh_pass: '{{ssh_pass}}'
            dest_path: "{{ {{dest_path}} | default('~/') }}"
        srv_03:
            ansible_host: 192.168.33.12
            ansible_user: '{{ssh_user}}'
            ansible_ssh_pass: '{{ssh_pass}}'
            dest_path: "{{ {{dest_path}} | default('~/') }}"
        srv_04:
            ansible_host: 192.168.33.13
            ansible_user: '{{ssh_user}}'
            ansible_ssh_pass: '{{ssh_pass}}'
            dest_path: "{{ {{dest_path}} | default('~/') }}"
        local:
            ansible_connection: local
    children:
        web_srv_group:
            hosts:
                srv_01:
                srv_02:
                srv_03:
                srv_04:
