services:
    flask-app:
        build:
            context: ../flask
            dockerfile: Dockerfile
        container_name: flask_app
        ports:
            - '5000:5000'
        networks:
            - app-network

    nodejs-app:
        build:
            context: ../nodejs
            dockerfile: Dockerfile
        container_name: nodejs_app
        ports:
            - '3000:3000'
        networks:
            - app-network

    springboot-app:
        build:
            context: ../springboot
            dockerfile: Dockerfile
        container_name: springboot_app
        ports:
            - '8080:8080'
        networks:
            - app-network

    golang-app:
        build:
            context: ../golang
            dockerfile: Dockerfile
        container_name: golang_app
        ports:
            - '9000:9000'
        networks:
            - app-network
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
