services:
    elasticsearch1:
        container_name: elasticsearch1
        hostname: elasticsearch1
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn1
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx2g -Xms2g
        ports:
            - '9200:9200' 
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk

    elasticsearch2:
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn2
        container_name: elasticsearch2
        hostname: elasticsearch2
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx2g -Xms2g 
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - efk

    elasticsearch3:
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3_cn3
        container_name: elasticsearch3
        hostname: elasticsearch3
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx2g -Xms2g 
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - efk

    kibana:
        hostname: kibana
        image: maverick0809/bitnami_kibana_tls:8.15.3v1
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/kibana/config
            ENCRYPTION_KEY: ${XPACK_ENCRYPTION_KEY}
            KIBANA_ELASTICSEARCH_URL: 'https://elasticsearch:9200'
            KIBANA_URL: https://0.0.0.0:5601
            KIBANA_HOST: 0.0.0.0
            KIBANA_PORT_NUMBER: 5601 
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        healthcheck:
            test: curl -s -k https://kibana:5601 > /dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
            - '5601:5601'
        networks:
            - efk
        depends_on:
            - elasticsearch1
            - elasticsearch2
            - elasticsearch3
    

    fluentd:
        image: maverick0809/bitnami_fluentd_tls:1.17.1v1
        user: '0:0'
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
            ELASTIC_HOST: ${ELASTIC_HOST}
            ELASTIC_URL: 'https://${ELASTIC_HOST}:9200'
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers  
        depends_on:
            - elasticsearch1
            - elasticsearch2
            - elasticsearch3
        networks:
            - efk 

networks:
    efk:
        driver: bridge
