services:
    elasticsearch:
        hostname: elasticsearch
        image: maverick0809/elasticsearch_tls:7.16.0
        restart: unless-stopped
        environment:
            ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
            bootstrap.memory_lock: 'true'
            discovery.type: single-node
        volumes:
            - elasticsearch_data:${ELASTIC_DIR}
        ports:
            - '9200:9200'
        healthcheck:
            test: curl -s https://elasticsearch:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk_overlay

    kibana:
        hostname: kibana
        image: maverick0809/kibana_tls:7.16.0
        restart: unless-stopped
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
            ENCRYPTION_KEY: ${XPACK_ENCRYPTION_KEY}
            KIBANA_URL: ${KIBANA_URL}
        healthcheck:
            test: curl -s https://kibana:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
            - '5601:5601'
        networks:
            - efk_overlay
        depends_on:
            - elasticsearch

networks:
    efk_overlay:
        driver: overlay
volumes:
    elasticsearch_data:
