CSRF='ZWJ9svkw-zdZgLNoDKlCGLJM1486MTczMTMxNDg2NzA0NDA1NjEwNw'
MINIO_ROOT_USER='minioadmin'
MINIO_ROOT_PASSWORD='minioadminpassword'
MINIO_URL='http://wsl.local:9001'
MINIO_ENDPOINT = 'minio:9000'
MINIO_USE_SSL = 'false'
GITEA_CONFIG='/home/git/gitea/gitea/conf'