services:
    elasticsearch:
        hostname: elasticsearch
        image: maverick0809/bitnami_elasticsearch_tls:8.15.3
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/elasticsearch/config
            ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP} 
        ports:
            - '9200:9200'
        healthcheck:
            test: curl -s -k https://elasticsearch:9200 > /dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 200000
                hard: 200000
        networks:
            - efk

    kibana:
        hostname: kibana
        image: maverick0809/bitnami_kibana_tls:8.15.3
        user: '1001:1001'
        restart: unless-stopped
        environment:
            CONFIG_DIR: /opt/bitnami/kibana/config
            ENCRYPTION_KEY: ${XPACK_ENCRYPTION_KEY}
            KIBANA_URL: https://0.0.0.0:5601
            KIBANA_ELASTICSEARCH_URL: 'https://elasticsearch:9200'
            KIBANA_HOST: 0.0.0.0
            KIBANA_PORT_NUMBER: 5601 
        healthcheck:
            test: curl -s -k https://kibana:5601 > /dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
            - '5601:5601'
        networks:
            - efk
        depends_on:
            - elasticsearch

    fluentd:
        image: maverick0809/bitnami_fluentd_tls:1.17.1
        user: '0:0'
        environment:
            ELASTIC_USERNAME: ${ELASTIC_USERNAME}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers 
            # - ./fluentd/init.sh:/docker-entrypoint-initdb.d/init.sh
            - ./fluentd/fluentd.conf:/opt/bitnami/fluentd/conf/fluentd.conf
        depends_on:
            - elasticsearch
        networks:
            - efk

    nginx:
        image: nginx
        container_name: nginx
        # logging:
        #     driver: "fluentd"
        #     options:
        #         fluentd-address: "fluentd:24224" 
        #         tag: "nginx"
        ports:
            - '8080:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - efk

networks:
    efk:
        driver: bridge
volumes:
    elasticsearch_data:
        driver: local
    elasticsearch_conf:
        driver: local
    fluentd_conf:
        driver: local
    kibana_data:
        driver: local
    kibana_conf:
        driver: local
